### ISSUE TITLE
How chat works?

### ISSUE THREAD

**Issue by danrobi11** [pinnaculum/galacteek#10]
Im in chat now alone I think.
Is chat public or I need to send invite?

**Comment by pinnaculum** [comment]
Not alone i saw your message ;)

> (2020-04-30 18:06) #general danrobi@Earth@KsqgkBG7XfYstG: hello

There's no need to send any invite. At the moment it's very basic, there's only one channel which is *general*

**Comment by danrobi11** [comment]
I restarted Galacteek and chat does not seems to be working
I do not log in chat when I open chat and when I type some it doesnt show up in chat.
Blog and feed working as intended

**Comment by danrobi11** [comment]
Is chat relying on a centralized server or its peer-to-peer only?

**Comment by pinnaculum** [comment]
It works peer-to-peer, it uses the IPFS pubsub (publish/subscribe) API

**Comment by danrobi11** [comment]
im running new appimage Galacteek-ff707ef9-x86_64
Chat works fine when running Galacteek as standalone. Chat wont work when running Galacteek with ipfs-desktop.

**Comment by pinnaculum** [comment]
This is because by default, ipfs-desktop does't enable the pubsub API when starting its go-ipfs daemon. To make ipfs-desktop enable pubsub, edit the file ~/.config/IPFS Desktop/config.json and look for the "ipfsConfig" section, and then "flags". You need to add this flag (put it first probably) in the list: *--enable-pubsub-experiment*

When you let galacteek spawn a daemon (in standalone as you say) it enables pubsub by default, that's why you don't see the issue in this case. Soon probably pubsub will  be enabled by default in go-ipfs.

**Comment by danrobi11** [comment]
Chat is working here now with: 
```
"--enable-pubsub-experiment",
```
Thank you!

**Comment by danrobi11** [comment]
hello plz get in the galacteek chat right now. got the owner of lokinet trying galacteek right now in chat

**Comment by danrobi11** [comment]
If you're running Galacteek with the IPFS-desktop daemon, you need to do this:

Edit the file ~/.config/IPFS Desktop/config.json and look for the "ipfsConfig" section, and then "flags". You need to add this flag (put it first probably) in the list: 

Put it first "--enable-pubsub-experiment", 
It should look like this:
    "flags": [
        "--enable-pubsub-experiment",

Edit the file ~/.ipfs/config and look for the "Pubsub" section and add gossipsub at "Router" 
It should be looking like this: "Router": "gossipsub",

**Comment by pinnaculum** [comment]
No problems with gossipsub ?

**Comment by danrobi11** [comment]
cant see you anymore

**Comment by pinnaculum** [comment]
Use floodsub then, as it seems message delivery rate was much better.

**Comment by danrobi11** [comment]
Im there with floodsub waiting to see you in 'peers'

**Comment by danrobi11** [comment]
Maybe I dont put floodsub and leave it empty?

**Comment by danrobi11** [comment]
you're gone now, normal?

**Comment by pinnaculum** [comment]
Thanks for putting the pubsub configuration for ipfs-desktop. As you can see pubsub is not always reliable, message drops are not unusual.

Closing the issue

**Comment by danrobi11** [comment]
I'd like to make sure I got the right settings when running with the galacteek daemon.
- routing mode: dht
- Pubsub routing: floodsub
- Writable HTTP gateway: enable
- Enable IPNS over Pubsub: disable
Correct?

**Comment by pinnaculum** [comment]
Yes that's correct these are the default settings. You can give a try to IPNS over pubsub as this feature is getting more stable now.

**Comment by danrobi11** [comment]
I disabled 'Enable IPNS over Pubsub' And I now see myself again in the peers section

**Comment by danrobi11** [comment]
When theres a new message in chat a notification in the chat tab (1) would help. If galacteek icon in taskbar or systray could blink that would be useful.

**Comment by danrobi11** [comment]
I cant receive any feed with normal reader client with this config:
routing mode: dht
Pubsub routing: floodsub
Writable HTTP gateway: enable
Enable IPNS over Pubsub: disable

**Comment by danrobi11** [comment]
Really nice the new chat, really like it :+1:

**Comment by pinnaculum** [comment]
Hello @danrobi11, yes there's been a first implementation of multi-channel chat, would be nice if we can test it. One thing still missing is to have better notifications in the UI for missed messages.

The channels list is distributed between peers (using basic CRDT)

#galacteek

**Comment by danrobi11** [comment]
here for you https://ipfs.io/ipfs/bafybeiazlk3wkgft27syigmqnmv76xzwf7dzgshehnwjnhtd5nl3ppjcxm

**Comment by danrobi11** [comment]
Is chat P2P ?
Answer:
Yes, chat is using pubsub: https://blog.ipfs.io/25-pubsub/
- pubsub means publish-subscribe. You subscribe to a topic, and then you'll receive all messages sent on that topic for example there's a pubsub topic called 'galacteek.chat' the messages are not persisted anywhere (no storage)

**Comment by danrobi11** [comment]
Hello. I think notification-tab does not go away if you leave before I see the messages. I might be wrong but its been same twice with same result. It did work when you were still in the chat, the notification went away.
I see the 'new users'  message in chat but I havent seen anybody but you in peers.
https://ipfs.io/ipfs/bafybeibzac4jz33oggekjehj2ka7rccwh2i4qyw5kzidrcmed3tj6njnmy
