### ISSUE TITLE
How blog and feed subscription works? (Solved)

### ISSUE THREAD

**Issue by danrobi11** [pinnaculum/galacteek#11]
I've created a blog and subscribed to the feed
Is this the address I need to give in order for users to subscribe to my post?
danrobi@Earth@KsqgkBG7XfYstG

**Comment by danrobi11** [comment]
I've read about the feed subscription from:  /atom.html#from-a-url
I've clicked on the 'rss feed icon' in the blog and it subscribed me automatically, correct?
Now, if I would like to manually subscribe or share the feed address which exact url that would be?
```
<?xml version='1.0' encoding='UTF-8'?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en">
  <id>ipns://bafzbeic7lfuf3sepkchvvzczzuocbb3jjzak4uerv36bhyplkdzt5uimpa</id>
  <title>danrobi@Earth@KsqgkBG7XfYstG's dweb space</title>
  <updated>2020-04-30T18:49:15.471098+00:00</updated>
  <author>
    <name>danrobi@Earth@QmfTBRKHoNfjnpY4eeWWUrCqJ5gz5HBiKsqgkBG7XfYstG</name>
  </author>
  <link href="ipns://bafzbeic7lfuf3sepkchvvzczzuocbb3jjzak4uerv36bhyplkdzt5uimpa/dfeed.atom" rel="self"/>
  <generator uri="https://lkiesow.github.io/python-feedgen" version="0.9.0">python-feedgen</generator>
  <entry>
    <id>ipns://bafzbeic7lfuf3sepkchvvzczzuocbb3jjzak4uerv36bhyplkdzt5uimpa/blog/galacteek-blog-post/view</id>
    <title>Galacteek Blog Post</title>
    <updated>2020-04-30T18:49:13+00:00</updated>
    <author>
      <name>danrobi@Earth@QmfTBRKHoNfjnpY4eeWWUrCqJ5gz5HBiKsqgkBG7XfYstG</name>
    </author>
    <link href="ipns://bafzbeic7lfuf3sepkchvvzczzuocbb3jjzak4uerv36bhyplkdzt5uimpa/blog/galacteek-blog-post/view" rel="alternate"/>
    <published>2020-04-30T18:49:13+00:00</published>
  </entry>
</feed>
```

**Comment by pinnaculum** [comment]
No, that would be the IP handle. The address of the Atom feed is

> ipns://bafzbeic7lfuf3sepkchvvzczzuocbb3jjzak4uerv36bhyplkdzt5uimpa/dfeed.atom

To subscribe to the Atom feed, the quickest is to click on the profile button, go to the Interplanetary Services menu, and click on 'IPS: Atom feed'. This will subscribe to the feed if not already subscribed to. You can also go to the *Peers* list, double click on your IP handle, and double-click on the *feed* IP service.

Your profile basically has an IP handle associated, as well as a DID (decentralized identifier, with the format *did:ipid:Qm....*). This DID has services associated to it, i call them IP services. The default services are the blog, feed, and a default collection service, which is like a simple container for files. You can publish files to this DID service from the filemanager (right click, *DID publish* submenu). You can also publish pyramids to your DID.

In galacteek peers exchange DID information over pubsub, so when other people are connected you' should see them in the peers section, and browse the services for each peer. So from there you can subscribe to the peer's feed. We can do a test some time in the next few days if you want.

**Comment by danrobi11** [comment]
I did same as I do with websites and I get this result:
```
ipfs resolve -r /ipns/bafzbeia5upr4rtfv7jm7vo677dheaotyj72mzoe36lq7bctcvpfojzcxai/How%20To%20MuWire%20Chat%20Functionality%20Demo.m4v: routing: not found
```
Is this because its a video or because I've added the video to my DID?

**Comment by danrobi11** [comment]
my new blog post address
ipns://bafzbeicv64lbgygcfht6ldmn6y2qltupnzwr6r4tbgyxc6ozxkc73ibxhy/dfeed.atom

**Comment by danrobi11** [comment]
im trying to access the blog post from normal web browsers

**Comment by danrobi11** [comment]
also cant subscribe to blog feed from a regular feed reader, I've tried with the URL above.

**Comment by pinnaculum** [comment]
I was able to access your blog from the IPNS address, so the IPNS publish worked at lease once, it's just very slow and random because of the network these days.

The Atom feed that galacteek produces contains URLS that use the *ipns://* scheme, it's meant to be read with galacteek or a feed reader that can fetch the objects from IPFS (i don't know any feed reader that does). Probably soon there'll be a second Atom feed, that generates URLS using public IPFS gateways so that you can use any feed reader

**Comment by danrobi11** [comment]
regarding: (we're all over the palce again)
'Also there are two atom feeds produced, one with pure IPFS URLs and one with URLs that use a public ipfs gateway, to be used with any feed reader (tested with rssguard), the filename is dfeed.publicgw.atom'

It seems like only the blog head line gets sync to public feed with regular feed reader.
I cant see the full blog post here in thunderbird. Same on your end with the rssguard?

**Comment by danrobi11** [comment]
Blog post preview blinking because image markdown
https://ipfs.io/ipfs/bafybeihjp4d4eyzm5v323rylq6f3y76xaynrotp43fvuhwljeitwzzxnlm

**Comment by danrobi11** [comment]
Hello. Reply to blog post possible?

**Comment by pinnaculum** [comment]
Not possible to reply to a blog post right now

**Comment by pinnaculum** [comment]
For blog posts, you can use the following URL schemes ipfs:// or ipns:// or dweb:// or http(s)://

I confirm that i can reproduce the issue with images blinking in the preview. When you post it it works though, i'll provide a fix for that soon.
