### ISSUE TITLE
Editor no session created

### ISSUE THREAD

**Issue by danrobi11** [pinnaculum/galacteek#13]
im running new appimage Galacteek-ff707ef9-x86_64
When I open Editor I have current session: No session yet.
Samething if I run Galacteek as standalone or with ipfs-desktop

**Comment by pinnaculum** [comment]
Until you make a change to a file contained in the object, it will say 'No session yet'. Once a file is changed and saved, the editor imports the directory, generating a new CID. At that point it will show the current object URL in the *Current session* label. Maybe the label should be hidden until there are some changes commited

**Comment by danrobi11** [comment]
Ok got it working. Thats what I had to do:
https://ipfs.io/ipfs/Qmatf4rKWGkM2ix6hAT9t6GSSRhF8NvmgWuRbHyZT39r5j?filename=No-session-yet2-2020-05-02_20.15.44.mp4

**Comment by pinnaculum** [comment]
In the video when you do the first save, it should have worked (and added it in the history and update the current session). I haven't been able to reproduce it. Was there an error/traceback in the terminal, if you ran the image from a term ?

**Comment by danrobi11** [comment]
well weird enough cant reproduce it either. I clicked on the 'save'  and it worked. It also open a new tab. 
```
[2020-05-03 15:00:43.487445] INFO: galacteek.ui.resource: /ipfs/bafybeia4ldt5u44ea65lsphwda4z363o4lezw4jkornce4pjhcyhtjib34 (inode/directory): opening
```

**Comment by danrobi11** [comment]
Ability to add new edited project from the editor to hashmark. What do you think? 
Im not running any pyramid because 'publish failed' so I was kind of stuck. So I copied the CID and downloaded the new edited project.

**Comment by pinnaculum** [comment]
Yes i agree this would be nice.
