### ISSUE TITLE
No preview in editor

### ISSUE THREAD

**Issue by danrobi11** [pinnaculum/galacteek#16]
Editor does not render webpage preview. Editor does not like html
https://ipfs.io/ipfs/bafybeia6n6a3ufkmbjukcnamexhgis6kng27o7t7hpb7zm2sx7peqgfdii

**Comment by danrobi11** [comment]
If this is some what related, just close the issue :) 
https://gitlab.com/stavros/IPFessay/-/issues/14

**Comment by pinnaculum** [comment]
Not at all related. The editor renders a preview only for markdown for now. It will do the same for HTML in the near future.

**Comment by pinnaculum** [comment]
@danrobi11 HTML preview will work with the latest AppImage (catalyst) updated just now. Other things have been implemented: bandwidth usage and peers graphs (just hover the ipfs rolling cube at bottom right and the status widget should appear), and the ability to push objects from the editor to a pyramid (a button appears in the editor history when you commit changes).

**Comment by danrobi11** [comment]
Nice! The status widget is really nice feature 👍
HTML not rendering as it should 100% Its much better now tho.
You can test with this file if you want:
https://ipfs.io/ipfs/bafybeiedr3hhamecodvkql7sqjm33zp3nif2bjidqhltnb6cnrf3az4khu
Open it in a browser to see how it exactually look.  Download it and edit from the editor and look the preview.

**Comment by danrobi11** [comment]
Im wondering. When I click 'save' in the editor. Theres this 'publish' button there. If im going to add the file in my pyramid do I need to click 'publish' ?
Speaking of pyramid. I edited my webpage that was in my pyramid. I flushed what was in the pyramid, put the edited file back into the pyramid. I can see the new edited file in my pyramid. But it gives me always the old not edited file. Is this because pubsub issue? I edited yesterday, still gives me the old webpage.

**Comment by pinnaculum** [comment]
Thank you. For HTML rendering there's just one change needed to make it render images. The preview widget uses a lightweight renderer (doesn't use qtwebengine but maybe we'll use it soon). I'll also add a way to only have the preview shown.

So what happens is, when you save content with the editor, it imports content in the IPFS repository but in 'offline' mode (it's not announced on the network). When you click on the "Publish" button, it announces that content to the network (it can be someties slow, it'll put a green OK when done). That means you can edit things "locally" and only publish what you want.

When you push something to the pyramid it will do an IPNS publish (on local and global DHTs with this version of go-ipfs), and although it's quite fast for the IPNS key to be updated "locally", it's not instant and can take up to 30 seconds or more in my tests, so expect some delay in the updates.

**Comment by pinnaculum** [comment]
@danrobi11 I joined the Github sponsors program, you can now easily [sponsor galacteek](https://github.com/sponsors/pinnaculum) ! Become the first one :)

**Comment by danrobi11** [comment]
Regarding the 'the status widget' its not reporting any activities and the galacteek systray icon report 'no connection available' while I know im connected.  Galacteek-45be9efc-x86_64.AppImage

**Comment by pinnaculum** [comment]
Issue fixed, that's because *Swarm.DisableBandwidthMetrics* was set to true when running in standalone.

The editor now uses qtwebengine for document previews (HTML previews should be much better and support ipfs links). Also there's a switch for offline/online publishing.

**Comment by danrobi11** [comment]
Status widget activities and editor preview are both working as intended. Thank you!

**Comment by pinnaculum** [comment]
You're welcome, thanks for your support :+1:
