### ISSUE TITLE
(Feature Request) Flathub and AppImageHub

### ISSUE THREAD

**Issue by danrobi11** [pinnaculum/galacteek#17]
Flathub and AppImageHub would increase visibility for Galacteek
https://www.appimagehub.com/
https://flathub.org/

**Comment by pinnaculum** [comment]
That's a good suggestion, thanks.

It's already registered on the other [AppImageHub](https://appimage.github.io/Galacteek/) but i'll definitely advertise it soon on appimagehub.com, great hub. There's no flatpak image yet but this could be done. I really like AppImage !

**Comment by pinnaculum** [comment]
Seems to be a tedious process to register it on appimagehub.com, i'll keep it mind though.
