### ISSUE TITLE
Feedback update

### ISSUE THREAD

**Issue by danrobi11** [pinnaculum/galacteek#18]
Config: default
- I received your new blog post in my feed client: Multi-channel chat with pubsub and CRTD and test4
Although, I dont see you in my galacteek feed. As for my personal blog feed I do receive them in galacteek and in the client.
- I installed galacteek on another device here under same config and we dont see eachother in chat nor in peers. 

Edit: Well thats weird. For more than 10hrs I couldnt see my other device anywhere. I havent change anything and now I see it in peers, 10hrs later.

**Comment by pinnaculum** [comment]
Hi @danrobi11 

There's been an important improvement regarding IPNS resolving, everything that depends on IPNS links will be faster. Please try the new image.

[continous catalyst images](https://github.com/pinnaculum/galacteek/releases/tag/continuous-catalyst)

**Comment by danrobi11** [comment]
Here lets see if theres drop: https://ipfs.io/ipfs/bafybeifbpdx24rolpwsnomw3coupxuleafbiug7nvczvjswcpu7e2vqtla

Hard for me to make sense of I do see you in #galacteek but I cant see my other device(nicky) in #danrobi 
I do see nicky in feed and sometimes in peers but not in chat room

**Comment by pinnaculum** [comment]
I do see the peer corresponding to this other device in the peers list. I've never tried running multiple instances of galacteek behind a NAT, in theory it should work but it depends on the configuration of your network router (do you use upnp ?)

Can you try the [0.4.22 release](https://github.com/pinnaculum/galacteek/releases/tag/v0.4.22) ?

**Comment by danrobi11** [comment]
Hello. Im running new 0.4.22
I noticed the new notification message in room tab and the new hashmark option in editor, very nice thank you :+1: 
As for now I havent seeing you nor nicky in peers/chat since I've updated. Which is weird because orbit working fine. 
Its unfortunate for Blog and Feed  that we dont see users in peers because blog/feed working fine.

**Comment by danrobi11** [comment]
saw this in terminal:
```
[10366:10829:0510/205959.685523:ERROR:nss_util.cc(748)] After loading Root Certs, loaded==false: NSS error code: -8018
```

**Comment by danrobi11** [comment]
Hello. I see your messages in #galacteek. Notification in tab does not go away.

**Comment by danrobi11** [comment]
I've tried to test pyramid by editing to see if it would sync new edit.
Pyramid does not work here 'publish failed' so I cant test. So I clicked on 'publish' in edit after 'save' 
I copy the address in clipboard. It does work in galacteek but not in regular browser.
/ipfs/bafybeih3lbwi5u63u5w5bungbiwzstysvolhyemumgkzx3mco5czbg7sjy
I did tried with https://ipfs.io/bafybeih3lbwi5u63u5w5bungbiwzstysvolhyemumgkzx3mco5czbg7sjy
and with: https://ipfs.io/bafybeih3lbwi5u63u5w5bungbiwzstysvolhyemumgkzx3mco5czbg7sjy/test-sync-edit
Nothing of the above working in normal browser

**Comment by pinnaculum** [comment]
I can't log in in Orbit (wheel keeps spinning), better use #ipfs on freenode's IRC. I have no issues with pyramid publishing. 

I can access /ipfs/bafybeih3lbwi5u63u5w5bungbiwzstysvolhyemumgkzx3mco5czbg7sjy. The ipfs.io links you show don't have the /ipfs/ prefix, it works using the gateway.

**Comment by pinnaculum** [comment]
If you run two instances of galacteek on the same network, you should "bootstrap" the two IPFS nodes together, that is, add the swarm address of one of the daemons in the other daemon's bootstrap list (in the config file). This will make pubsub work on both instances.

**Comment by danrobi11** [comment]
Hello. I tried pyramid again and its working now. I edited a webpage and it gave me the edited version so thats good. 
Now this bootstrap thingy sounds a bit thechy.
I went in .local/share/galacteek/main/ipfs/config and I see this:
```
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
   "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
```
What I copy/ paste where?

**Comment by pinnaculum** [comment]
On the first ipfs daemon, run the command *ipfs id*, and in the *Addresses* section, there will be one or two swarm multiaddr (don't use the one with *127.0.0.1*) it will look like *"/ip4/x.x.x.x/tcp/4001/p2p/Qm.......". Copy this in the bootstrap section of the other daemon.

**Comment by danrobi11** [comment]
Answer for the bootstrap (run multiple Galacteek instance in the same network)
In this example running 'ipfs id' in terminal gives this:
```
"/ip4/127.0.0.1/tcp/4001/p2p/QmWuT9UYTDrEphNEyLkm2PmtjUEiVihmWnB3figRnZWvgU",
    "/ip4/192.168.2.10/tcp/4001/p2p/QmWuT9UYTDrEphNEyLkm2PmtjUEiVihmWnB3figRnZWvgU",
    "/ip4/172.17.0.1/tcp/4001/p2p/QmWuT9UYTDrEphNEyLkm2PmtjUEiVihmWnB3figRnZWvgU",
    "/ip4/10.0.0.1/tcp/4001/p2p/QmWuT9UYTDrEphNEyLkm2PmtjUEiVihmWnB3figRnZWvgU",
    "/ip6/::1/tcp/4001/p2p/QmWuT9UYTDrEphNEyLkm2PmtjUEiVihmWnB3figRnZWvgU",
    "/ip4/70.51.197.213/tcp/34996/p2p/QmWuT9UYTDrEphNEyLkm2PmtjUEiVihmWnB3figRnZWvgU"
```
The current local network is: 192.168.2.10
So this is the line that needs to be added in the other daemon's bootstrap section:
"/ip4/192.168.2.10/tcp/4001/p2p/QmWuT9UYTDrEphNEyLkm2PmtjUEiVihmWnB3figRnZWvgU",

**Comment by danrobi11** [comment]
Hello Im in galacteek I often see you in peers. Do you see me too? Because I dont see myself in peers nor in chat rooms.
Subscribe to my blog and we could talk. Im subscribed to your cipres@Saturn feed.
- https://ipfs.io/ipns/bafzbeidtceytxwx33umnm67m7pnpnuowmogei275hshwnpf3gmtl4wifri/dfeed.publicgw.atom

I re-installed my OS. I did like you told me to and its working for 1 pyramid but the other pyramid not loading in normal browser, does load in galacteek tho. I've check the path and path is the same. I dont see why the second pyramid not loading in normal browser.

**Comment by pinnaculum** [comment]
Hello,

You don't appear in the peers list no, this could be related to a problem with pubsub, if you reinstalled your OS, maybe you didn't set up the IPFS daemon the way it was before ? Access to your blog/feed works though. Did you make a backup of your ~/.local/share/galacteek and copy that over ?

What do you mean by "edit the path of our pyramid" ?

**Comment by pinnaculum** [comment]
Something is wrong with your profile. Please run galacteek with **-d** and copy/paste the debug output in a pastebin somewhere.

**Comment by danrobi11** [comment]
I dont know about pastebin so I put output in text file:

/ipfs/bafybeieecain5xtwpcer2axlhdbnomnwg5sjlqmu7qfijsj3ihmxm67wiy

**Comment by pinnaculum** [comment]
Thank you. Your DID cannot be loaded:

> [2020-06-22 17:10:43.183834] DEBUG: galacteek.did.ipid: IPID (local) (did:ipid:Qmbc2kTX9XmudAm4QDeDAJXtYqM57yhLgZrDYZpQm4mq1x): Failed to resolve ?
[2020-06-22 17:10:43.184272] DEBUG: galacteek.ipfs.pubsub.service: Failed to load local DID

This explains why you don't appear in the peers list.

This most certainly occurs because you reinstalled everything and have lost the IPNS keys corresponding to your DID from your ipfs repos. Unless you can recover them the easiest will be to recreate a new DID.

**Comment by danrobi11** [comment]
ok sounds good. How to create new DID?

**Comment by pinnaculum** [comment]
Click the profile button (helmet icon), then select *Edit profile*, click on the *lock* icon, change the username/planet and click on *Update*, this will generate a new DID.

**Comment by danrobi11** [comment]
Yep, working. Thank you!
This does not fix my 2nd pyramid. Why I was thinking about editing pyramid path would fix its because, I have 'this site cant be reached' inside galacteek even tho path seems fine and pyramid 1 is working flawlessly. So I dont know

**Comment by pinnaculum** [comment]
Can you restart the browser to see if your DID works now ? It still doesn't seem to be sending peer identification messages via pubsub. Your problem with the pyramid is also most likely related to the reinstallation (objects related to the pyramid are gone)

**Comment by danrobi11** [comment]
I did restart galacteek. Thats how I managed to see myself in peers and char room. Wasnt working before restart.

**Comment by danrobi11** [comment]
output with new DID:
/ipfs/bafybeihnignexxusq4ch5tfsynluxh4glohpgqfvt7l26xeb4kbb3zfm6q

**Comment by pinnaculum** [comment]
Seems all good now, your DID is correctly loaded.

**Comment by danrobi11** [comment]
cool thank you. see u in chat :)

**Comment by danrobi11** [comment]
Created new pyramid and exact same result. Worked in galacteek only, never worked in normal browser. Edited twice the new pyramid. After the second edit, new pyramid does not work in galacteek anymore. So exact same thing.

**Comment by danrobi11** [comment]
Migration files:
$HOME/.local/share/galacteek/main
$HOME/.config/galacteek

**Comment by danrobi11** [comment]
Hello. r u ok? long time didnt see ya
