### ISSUE TITLE
Feedback and ideas

### ISSUE THREAD

**Issue by serejandmyself** [pinnaculum/galacteek#21]
Hey! Looks awesome. Would love to connect with you, seems like we are on the same path more or less. 

We are doing this: https://github.com/cybercongress/go-cyber

cyber.page/brain/docs

**Comment by pinnaculum** [comment]
Hello @serejandmyself thank you!

Yes i know about cyber it's quite amazing ! I've tried cyb and i remember trying to find ideas on how to integrate galacteek with the cyber engine that would be awesome. Right now searches go through the ipfs-search.com service.

Do you have any ideas in mind ?

**Comment by serejandmyself** [comment]
@pinnaculum 

Good question 😊

1) You can use our endpoints to add cyber as a search engine to your browser (currently there are over 200,000 CIDs and growing)

2) RPC API: https://titan.cybernode.ai/api
Search API: https://titan.cybernode.ai/search?cid=_&page=_&perPage=_ (CID is computed from a buffer string with a human request in this case)
Swagger(LCD): https://lcd.cyber.cybernode.ai/swagger-ui/

3) One thing is search, but the real power of cyber is that it can index content. So if you utilize a wallet and a signer python library and add the ability to sign transactions, your browser will gain blockchain superpowers =)

4) Of course you will need a wallet and some UI for that. There is dot.cyber application: https://github.com/cybercongress/dot-cyber
Hope cyber.page will inspire you. I am going to reference to some user guides, sorry for this, but its a good way to see the amount of capabilities it has: https://github.com/cybercongress/congress/blob/master/ecosystem/Cyber%20Homestead%20doc.md#using-cyberpage-for-masters 

5) We are also open to suggestions on how we can benefit from the amazing things that you did here, if you have any ideas!

**Comment by pinnaculum** [comment]
Awesome, thanks for your input !

Adding cyber as a search engine would probably be the first step. For the *search* endpoint, i've read that the passed CID can be a CIDv0 or CIDv1, does it automatically do a "v0 to v1" conversion and always use the CIDv1 as the index ? Is it correct to pass a CIDv1 in base32 ?

Point 3. will take more work but would be worth it. I'll create an issue soon.

**Comment by serejandmyself** [comment]
@pinnaculum For now both are good
You can link v0-v0, v0-v1, v1-v0, v1-v1
They will all be searchable in the same way, for now =)

BTw, one more thing we thought about. Our community is rather small, but they are all big decentralization enthusiasts and would love to know more about projects like yours!

If you want, we can do some kind of an AMA about your project after you integrate cyber search so we can relate to them. I mean in our TG channel or something. Unsure that it will be a big boost for you, but we you may find this interesting. After all, we would like to start partnering with search browsers and crawlers like your own :-)

**Comment by pinnaculum** [comment]
As you saw search with cyber has been implemented in v0.4.29. I've created [an issue](https://github.com/pinnaculum/galacteek/issues/23) for improving the search UX feel free to share ideas there.

**Comment by serejandmyself** [comment]
@pinnaculum I will need a bit more time of personal use of galacteek and will start adding various ideas for the UX feel to #23 . Shall we close this one?

**Comment by pinnaculum** [comment]
Sure! Yeah i'll close this one.
