### ISSUE TITLE
Cant reach ipfs address

### ISSUE THREAD

**Issue by danrobi11** [pinnaculum/galacteek#22]
Hello
Cant reach this in galacteek: https://docs.ipfs.io/

**Comment by pinnaculum** [comment]
Hello,

Both [https://docs.ipfs.io/](https://docs.ipfs.io/) and [ipns://docs.ipfs.io](ipns://docs.ipfs.io) seem to work, do you get any specific error ?

**Comment by danrobi11** [comment]
Yes, you're right, its working here now. My bad. Closing.
