### ISSUE TITLE
Feature Request: Official Android Build

### ISSUE THREAD

**Issue by StationedInTheField** [pinnaculum/galacteek#29]
apparently it's not too hard to build galacteek as an android app.

https://medium.com/@Lola_Dam/packaging-pyqt-application-using-pyqtdeploy-for-both-linux-and-android-32ac7824708b

**Comment by pinnaculum** [comment]
There are a few obstacles ... First you'd need to have go-ipfs running natively and smoothly on android, i don't think it's really supported yet.

Then there's all the work of adapting the UI ... i don't see it happening soon.

I close this in the meantime, thanks for the idea though.
