### ISSUE TITLE
Can't select local node from first run dialog

### ISSUE THREAD

**Issue by teknomunk** [pinnaculum/galacteek#31]
When I first started galacteek for the first time, it prompted me for settings to start an IPFS node. I am already running an IPFS node on the same system. The default options conflict with the already running ipfs daemon causing galacteek to loop trying to start an ipfs daemon. To break it out of this, I opened the settings dialog, unchecked "Spawn IPFS daemon and use as transport", the hard reset the application (ctrl-z, kill %1).

## Software version
0.4.37

## OS
archlinux x86_64

## IPFS daemon type (standalone/custom)
- [ ] Standalone
- [X] Custom IPFS daemon -> localhost

## Expected Behavior
There should be an option to configure a custom node

## Current Behavior
As there is no option to configure a custom node, and the default node options conflict with the default go-ipfs configuration, it will loop trying to start a node, but always fail.

## Steps to Reproduce
1. Start an ipfs daemon
2. Delete any existing galacteek configuration
3. Launch galacteek

## Possible Solution
Add an option to configure a custom IPFS node in the first run dialog

**Comment by pinnaculum** [comment]
Thanks a lot @teknomunk for all the details on this issue.

This will be fixed in the next release in a few days, with the solution you suggested.
