### ISSUE TITLE
Tab order on IPID generator is incorrect

### ISSUE THREAD

**Issue by teknomunk** [pinnaculum/galacteek#32]
When you select the "Passphrase" field, enter a password, then press Tab, it changes to the "Username" field, not the "Repeat passphrase" field.

## Software version
0.4.37

## OS
archlinux x86_64

## IPFS daemon type (standalone/custom)
- [ ] Standalone
- [X] Custom IPFS daemon -> localhost

## Expected Behavior
Pressing Tab when the "Password" field is selected should change to the "Repeat passphrase" field.

## Current Behavior
Pressing Tab when the "Password" field is selected changes to the "Username" field.

## Steps to Reproduce
1. Start IPID generator dialog
2. Select "Passphrase" field
3. Press "Tab"

**Comment by pinnaculum** [comment]
Thanks, i've fixed the tab order for the form.
