### ISSUE TITLE
Issue with v0.4.22-x86_64.AppImage

### ISSUE THREAD

**Issue by danrobi11** [pinnaculum/galacteek#35]
```
$ ./Galacteek-0.4.22-x86_64.AppImage
Traceback (most recent call last):
  File "/tmp/.mount_Galactfi93pT/usr/bin/galacteek", line 5, in <module>
    from galacteek.guientrypoint import start
  File "/tmp/.mount_Galactfi93pT/usr/lib/python3.7/site-packages/galacteek/guientrypoint.py", line 7, in <module>
    from PyQt5.QtWebEngine import QtWebEngine
ImportError: /tmp/.mount_Galactfi93pT/usr/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5Network.so.5: symbol _ZN15QIPAddressUtils8toStringER7QStringPh version Qt_5 not defined in file libQt5Core.so.5 with link time reference
```

## AppImage version
Galacteek-0.4.22-x86_64.AppImage

## Linux distribution
OS: MX 19.3 (patito feo) x86_64 based Debian GNU/Linux 10 (buster)
SysV init version: 2.93
Kernel: 4.19.0-9-amd64
Xorg v1:7.7+19
WM: Spectrwm

## Debug output with QT_DEBUG_PLUGINS=1
```
$ ./Galacteek-0.4.22-x86_64.AppImage QT_DEBUG_PLUGINS=1Traceback (most recent call last):  File "/tmp/.mount_GalactTwd3xI/usr/bin/galacteek", line 5, in <module>
    from galacteek.guientrypoint import start
  File "/tmp/.mount_GalactTwd3xI/usr/lib/python3.7/site-packages/galacteek/guientrypoint.py", line 7, in <module>
    from PyQt5.QtWebEngine import QtWebEngine
ImportError: /tmp/.mount_GalactTwd3xI/usr/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5Network.so.5: symbol _ZN15QIPAddressUtils8toStringER7QStringPh version Qt_5 not defined in file libQt5Core.so.5 with link time reference
```
## Debug output with APPIMAGE_LIBCHECK=1
```
$ ./Galacteek-0.4.22-x86_64.AppImage APPIMAGE_LIBCHECK=1
Traceback (most recent call last):
  File "/tmp/.mount_GalactiChkmL/usr/bin/galacteek", line 5, in <module>
    from galacteek.guientrypoint import start
  File "/tmp/.mount_GalactiChkmL/usr/lib/python3.7/site-packages/galacteek/guientrypoint.py", line 7, in <module>
    from PyQt5.QtWebEngine import QtWebEngine
ImportError: /tmp/.mount_GalactiChkmL/usr/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5Network.so.5: symbol _ZN15QIPAddressUtils8toStringER7QStringPh version Qt_5 not defined in file libQt5Core.so.5 with link time reference
```

**Comment by pinnaculum** [comment]
Hi @danrobi11 ,

The AppImage version that you mention, *0.4.22*, is a very old release, (latest is *0.4.41*, in a few days version *0.4.42* will be released). If it's not a typo and you're trying to run an old image, please provide the md5 checksum of the AppImage file.

**Comment by danrobi11** [comment]
> 0.4.22, is a very old release

Indeed! My bad. I went in galacteek matrix and saw a link. Thought was the new 4.42 

> in a few days version 0.4.42 will be released

Ok cool Thanks. Was wondering why only exe version.

**Comment by danrobi11** [comment]
I just tested new 4.42 
New dark theme looks pretty good . Thanks!

**Comment by pinnaculum** [comment]
Yes, [release 0.4.42](https://github.com/pinnaculum/galacteek/releases/tag/v0.4.42) brings UI changes, BitMessage support, and is also much more configurable although there's no documentation on the settings yet.

If you run into any issues please report it here, thanks.
