### ISSUE TITLE
Feature request: search bar in blog

### ISSUE THREAD

**Issue by danrobi11** [pinnaculum/galacteek#36]
I now have over 300 blog post. Very hard to go find a specific old post. A search bar would be handy

**Comment by pinnaculum** [comment]
You'll soon be able to migrate to the blog dapp, with support for comments and other things.

**Comment by danrobi11** [comment]
> with support for comments and other things

wow 🎉

**Comment by pinnaculum** [comment]
Closed (implemented in different module)

**Comment by danrobi11** [comment]
@pinnaculum 

> implemented in different module

Nice! 🎉

When my blog section broke. I've realized that I was able to reach all my blog post from the blog URL. Therefore, I can use the search option in galacteek or in any browser to find specific post. I had to break my blog to figure that out LOL. 
Any how, thank you much, that's a good addition 👍
