### ISSUE TITLE
PC crashed and now my blog is gone :/ help

### ISSUE THREAD

**Issue by danrobi11** [pinnaculum/galacteek#38]
Hi Cipres. My pc crashed and now my blog looks like this :/

![blog after pc crash](https://user-images.githubusercontent.com/48020114/115469684-17a19880-a203-11eb-9d1c-2bb947e4cd19.png)

**Comment by pinnaculum** [comment]
Sorry to hear that ... We'll have to assess first if the IPFS repos is corrupted or not. It's unlikely that your data has been lost, however some of the files in the MFS could be corrupted or lost.

Please open a bug report using [this form](https://github.com/pinnaculum/galacteek/issues/new?assignees=&labels=&template=bug-report.md), it makes it easier to manage.

First open a terminal and run the following (to select *galacteek*'s IPFS repository):

> export IPFS_PATH=$HOME/.local/share/galacteek/main/ipfs

Then get the output of the following commands (the *ipfs*binary should be in your $PATH):

- ipfs files ls -l /galacteek/profile.default/data/dag.main

- ipfs files read /galacteek/profile.default/data/dag.main|jq '.cidlatest'

- ipfs key list -l|grep galacteek.default.root

Please copy/paste the command outputs in the *Extra information* section of the bug report. None of these informations are sensitive, they are the CIDs of the main DAG, in which the public blog is stored.

In the bug report, it would also help to explain briefly what works and doesn't work after you rebooted:

- Does browsing any IPFS webpage work ? For example the manual, or ipns://ipfs.io
- Do your files still appear in the filemanager ?

Thank you very much.

**Comment by danrobi11** [comment]
command doesnt work. IPFS is not installed I run Galacteek as standalone

```
$ export IPFS_PATH=$HOME/.local/share/galacteek/main/ipfs
danrobi@mx-desktop:~
$ ipfs files ls -l /galacteek/profile.default/data/dag.main
bash: ipfs: command not found
danrobi@mx-desktop:~
$ ipfs files read /galacteek/profile.default/data/dag.main|jq '.cidlatest'
bash: ipfs: command not found
danrobi@mx-desktop:~
$ ipfs key list -l|grep galacteek.default.root
bash: ipfs: command not found
```
> Does browsing any IPFS webpage work ? For example the manual, or ipns://ipfs.io
Do your files still appear in the filemanager ?

Everything works. And yes I can access my blog from the URL address:
ipns://k2k4r8ma9cz95vz4sw0gn1wr6lng450u0uaowqsev8k24zghkfs17r0q/blog/index.html

**Comment by pinnaculum** [comment]
As root:

> wget https://dist.ipfs.io/go-ipfs/v0.8.0/go-ipfs_v0.8.0_linux-amd64.tar.gz
> tar -xvf go-ipfs_v0.8.0_linux-amd64.tar.gz
> cp go-ipfs/ipfs /usr/bin

Closed (please provide details in new issue)

**Comment by pinnaculum** [comment]
Closed

**Comment by pinnaculum** [comment]
.
