### ISSUE TITLE
Flatpak build 

### ISSUE THREAD

**Issue by LeandroStanger** [pinnaculum/galacteek#41]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing **galacteek** on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by pinnaculum** [comment]
Hi @LeandroStanger.

Flatpak is already supported and is actually the recommended installation method on Linux (AppImage and Flatpak are available). It is not distributed in any official flatpak repo, but rather as a flatpak bundle hosted on IPFS. See the [download page](https://galacteek.gitlab.io/download/) and [the flatpak bundle section in particular](https://galacteek.gitlab.io/download/#flatpak-bundle).

It was published on a private flatpak repo before but it's easier for me to distribute as a bundle on IPFS at the moment. Before that i had tried to [submit the app for Flathub](https://github.com/flathub/flathub/pull/2163) but the git repo dependency was an issue, it could be fixed though.
